# -*- coding: utf-8 -*-
"""workingexamples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ejPmAbZR7fnTqXBn_pBqrrZ8wgU1vbCn
"""

# libraries
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
 
# create data
x = np.random.rand(15)
print(len(x))
y = x+np.random.rand(15)
print(len(y))
z = x+np.random.rand(15)
print(len(z))

z=z*z

print("After")
print(z)


 
# Change color with c and alpha. I map the color to the X axis value.
plt.scatter(x, y, s=z*2000, c=x, cmap="Blues", alpha=0.4, edgecolors="grey", linewidth=2)
 
# Add titles (main and on axis)
plt.xlabel("the X axis")
plt.ylabel("the Y axis")
plt.title("A colored bubble plot")
 
plt.show()

x = [1, 2, 3]


y = [4, 5, 6]
z = x+np.random.rand(3)
z=z*z
x1 = np.linspace(0, 10, 1000)

figure, axes = plt.subplots(nrows=2, ncols=2)

axes[0, 0].plot(x, y)
#plt.scatter(x, y, s=z*2000, c=x, cmap="Blues", alpha=0.4, edgecolors="grey", linewidth=2)

axes[0, 1].scatter(x,y,s = z*20, c= x,cmap="Blues", alpha=0.4, edgecolors="grey", linewidth=2)
axes[1, 0].plot(x1, np.cos(x1))
axes[1, 1].plot(range(10))

figure.tight_layout()